#!/bin/sh

if [ $# -lt 1 ] ; then
echo -e "Wrong number of parameters."
echo -e "Usage:"
echo -e " build\n 'source' - php source directory, etc.: '~/php/php-5.4'\n"
exit 1
fi

if [ ! -d "$1" ]
then
    echo "Php source is not a valid directory"
    exit 1
fi

rm -rf apache_build cli_build && \
cp -r $1 apache_build && cp configure_apache apache_build/php_configure_src && \
cp -r $1 cli_build && cp configure_cli cli_build/php_configure_src && \
cd apache_build && ./php_configure_src && make && cd .. && \
cd cli_build && ./php_configure_src && make && cd ..
