#!/bin/sh

# used on Archlinux, dependencies are all module based, you need gcc and make tools
# note all additional libraries can be built and included later as extensions
# mysql and other extensions are built-in

# only cli_build will install php binary and other binaries in /usr/bin
# which is --prefix in the configure file

mkdir -p /usr/share/pear && \
rm -f /usr/lib/php/modules/*.a && \
rm -f /usr/lib/php/modules/{posix}.so && \
rm -f /usr/lib/httpd/modules/libphp5.so && \
cp -f apache_build/libs/libphp5.so /usr/lib/httpd/modules/libphp5.so && \
cp -f apache_build/modules/*.so /usr/lib/php/modules/. && \
cd cli_build && make install && cd ..
