#!/bin/zsh
#
# xmonad statusline, (c) 2007 by Robert Manea
#

# Configuration
DATE_FORMAT='%a %d %b %H:%M'
DZEN_ICONPATH=$HOME/.xmonad/icons

# Main loop interval in seconds
INTERVAL=1

# Functions
fdate() {
    icon="^i($DZEN_ICONPATH/clock.xpm)"
    today=$(date +$DATE_FORMAT)
    printf "^fg(white)%s %s^fg()" "$icon" "$today"
}

fgtime() {
    print -n "NY:" $(TZ='America/New_York' date +'%H:%M')
}


# BATTERY
fbattery() {
    infos=$(acpi -b)
    percent=$(echo $infos|sed "s/Battery .: [a-z]*, \([0-9]*\)%\(,.*\|$\)/\1/i")
    state=$(echo $infos|sed "s/Battery .: \([a-z]*\),.*/\1/i")
    if [ "$percent" -lt 5 ]; then modifier="^bg(#dc322f)^fg(white)"
    elif [ "$percent" -lt 20 ]; then modifier="^bg(#cb4b16)^fg(white)"
    elif [ "$percent" -lt 50 ]; then modifier="^fg(#b58900)"
    else modifier="^fg(#859900)"
    fi

    percent="$percent%"

#    case $state in
#        "Charging") sign="|+|";;
#        "Discharging") sign="|-|" ;;
#        "Unknown") sign=" ⚡";;
#        "Full") sign="⚡"; percent= ;;
#        *) sign="$state" ;;
#    esac

    sign="^i($DZEN_ICONPATH/power-bat.xbm)"

    printf "$modifier%s%s^fg()^bg()" "$percent" "$sign"
}

# LOAD AVERAGE

fload() {
    load=$(awk '{print $1}' /proc/loadavg)
    icon="^i($DZEN_ICONPATH/load.xbm)"
    printf "%s%.01f %s^fg()" "^fg(#6c71c4)" "$load" "$icon"
}


fmem() {
    # MEMORY

    memory=$(free | awk '/buffers\/cache:/ {printf "%.0f", 100*$3/($3 + $4)}')
    if [ "$memory" -gt 90 ]; then modifier="^bg(#dc322f)^fg(white)"
    elif [ "$memory" -gt 80 ]; then modifier="^bg(#cb4b16)^fg(white)"
    elif [ "$memory" -gt 70 ]; then modifier="^fg(#b58900)"
    else modifier="^fg(#859900)"
    fi

    icon="^i($DZEN_ICONPATH/mem.xbm)"
    printf "%s%s%% %s^fg()^bg()" "$modifier" "$memory" "$icon"
}

_cpu_temp() {
    # CPUs temp
    temp=$(sensors | awk -F+ '{print $2}' | grep 'crit' | awk -F. '{print $1}')
    if [ "$temp" -gt 80 ]; then
        modifier='^bg(#dc322f)^fg(white)'
    elif [ "$temp" -gt 60 ]; then
        modifier='^fg(#b58900)'
    else
        modifier='^fg(#859900)'
    fi
    printf "%s%s°C^fg()^bg()" "$modifier" "$temp"
}

_active_network_interface() {
    ACTIVE="none" # default to eth0 in case if none active
    for iface in  `ifconfig | egrep 'eth[0-9]|wlan[0-9]' | awk -F': ' '{print $1}'` ; do
        ifconfig $iface | grep -q 'inet ' && ACTIVE="$iface"
    done

    echo $ACTIVE
}

# network interface active
CURR_IFACE=$(_active_network_interface)

# Here we remember the previous rx/tx counts
RXB=`cat /sys/class/net/${CURR_IFACE}/statistics/rx_bytes`
TXB=`cat /sys/class/net/${CURR_IFACE}/statistics/tx_bytes`

while true; do
    PGTIME=$(fgtime)
    PDATE=$(fdate)
    PBAT=$(fbattery)
    LOAD=$(fload)
    MEM=$(fmem)
    TEMP=$(_cpu_temp)

    # use active network interface
    CURR_IFACE=$(_active_network_interface)
    if [ "$CURR_IFACE" != "none" ]; then
        # get new rx/tx counts
        RXBN=`cat /sys/class/net/${CURR_IFACE}/statistics/rx_bytes`
        TXBN=`cat /sys/class/net/${CURR_IFACE}/statistics/tx_bytes`

        # calculate the rates
        # format the values to 4 digit fields
        RXR=$(printf "%4d\n" $(echo "($RXBN - $RXB) / 1024/${INTERVAL}" | bc))
        TXR=$(printf "%4d\n" $(echo "($TXBN - $TXB) / 1024/${INTERVAL}" | bc))

        if [ $RXR -eq 0 ]; then
            rxColor=""
        else
            rxColor="#859900"
        fi

        if [ $TXR -eq 0 ]; then
            txColor=""
        else
            txColor="#dc322f"
        fi

        if [ "$CURR_IFACE" = "wlan0" ]; then
            # wifi
            netIcon="$DZEN_ICONPATH/net-wifi5.xbm"
        else
            # wired
            netIcon="$DZEN_ICONPATH/net-wired2.xbm"
        fi

        # print out the rates with some nice formatting
        echo -n "^i($netIcon)^fg(#859900)^fg($rxColor)${RXR} K^p(3)^i($DZEN_ICONPATH/arr_down.xbm)^fg($txColor)${TXR} K^i($DZEN_ICONPATH/arr_up.xbm)^fg() "

        # reset old rates
        RXB=$RXBN; TXB=$TXBN
    else
        # not connected
        netIcon="$DZEN_ICONPATH/net-wired.xbm"
        echo -n "^i($netIcon) "
    fi
    # Arrange and print the status line
    print "| $TEMP $PBAT $LOAD $MEM | $PGTIME $PDATE"

    sleep $INTERVAL
done
