#!/bin/zsh

# Script to lookup any kind of notes, listing by most often used ones
# requires dmenu compiled with XFT support for the font

source ${XDG_CONFIG_HOME:-$HOME/.config}/solarized/colors.ini

HIST="$HOME/.dmenu/notes_hist"
NOTE_PATH="$HOME/.notes"
FN="xft:Inconsolata:size=16"

[[ -d "$NOTE_PATH" ]] || {
    mkdir $NOTE_PATH
}

NOTE=$(ls $NOTE_PATH | cat | dmenu -i -nb $base03 -nf $base0 -sb $base02 -sf $orange -fn "$FN" -p "Note:" -hf "$HIST")

if [ "$NOTE" ]; then
    gvim "$NOTE_PATH/$NOTE"
fi
