#!/bin/zsh

projects=$(ls -l ~/.tmuxinator/| grep "^-" | awk {'print $9'} | cut -d. -f1)

source ${XDG_CONFIG_HOME:-$HOME/.config}/solarized/colors.ini

project=$(echo $projects | dmenu -i -nb $base03 -nf $base0 -sb $base02 -sf $orange -fn 'xft:Inconsolata:size=16' "$@" -p "TMUX workspace ")

[ -z "$project" ] && exit

mux "$project"
